definitions:
  CommonError:
    properties:
      message:
        description: |-
          Message of the error
          in: string
        type: string
        x-go-name: Message
      status:
        description: |-
          Status of the error
          in: int64
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: casapressione/controllers
  CommonSuccess:
    properties:
      message:
        description: |-
          Message of the error
          in: string
        type: string
        x-go-name: Message
      status:
        description: |-
          Status of the error
          in: int64
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: casapressione/controllers
  GetPressure:
    properties:
      data:
        $ref: '#/definitions/Pressure'
      message:
        description: |-
          Message of the response
          in: string
        type: string
        x-go-name: Message
      status:
        description: |-
          Status of the error
          in: int64
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: casapressione/controllers
  GetPressures:
    properties:
      data:
        $ref: '#/definitions/Pressures'
      message:
        description: |-
          Message of the response
          in: string
        type: string
        x-go-name: Message
      status:
        description: |-
          Status of the error
          in: int64
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: casapressione/controllers
  Pressure:
    properties:
      data_inserimento:
        description: |-
          Timestamp of insert
          in: time
        format: date-time
        type: string
        x-go-name: DateInsert
      id:
        description: |-
          Id of Pressure value
          in: int64
        format: int64
        type: integer
        x-go-name: Id
      valore:
        description: |-
          Value of Pressure
          in: float
        format: float
        type: number
        x-go-name: Value
    type: object
    x-go-package: casapressione/models
  Pressures:
    items:
      $ref: '#/definitions/Pressure'
    type: array
    x-go-package: casapressione/models
  ReqAddPressure:
    properties:
      valore:
        description: |-
          Value of the Pressure
          in: float
        format: float
        type: number
        x-go-name: Value
    type: object
    x-go-package: casapressione/models
info:
  title: 'Pressure Api:'
  version: 0.1.1
paths:
  /lasthour:
    get:
      description: Get list of last hour of pressure values .... or the last value
        inserted
      operationId: lastHour
      responses:
        "200":
          description: GetPressures
          schema:
            $ref: '#/definitions/GetPressures'
        "401":
          description: CommonError
          schema:
            $ref: '#/definitions/CommonError'
      security:
      - apiKey:
        - '[]'
  /pressure:
    post:
      description: Create a new pressure value
      operationId: addPressure
      responses:
        "200":
          description: GetPressure
          schema:
            $ref: '#/definitions/GetPressure'
        "401":
          description: CommonError
          schema:
            $ref: '#/definitions/CommonError'
      security:
      - apiKey:
        - '[]'
  /pressures:
    get:
      description: Get Pressure list
      operationId: listPressure
      responses:
        "200":
          description: GetPressures
          schema:
            $ref: '#/definitions/GetPressures'
        "401":
          description: CommonError
          schema:
            $ref: '#/definitions/CommonError'
      security:
      - apiKey:
        - '[]'
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
